language: python
python:
 
#Install dependencies
install:
  - pip install -r requirements.txt
  - pip install pip 
  - pip install flask
  - sudo apt-get update
  - sudo pip install requests

#Run Tests
before_script:
  - cd ClientAndServerTesting
  - pip install flask
script:
  - python3 RequestTest.py
