language: python
python:
 
#Install dependencies
install:
  - pip install -r requirements.txt
  - pip install pip 
  - sudo apt-get update
  - sudo pip install requests

#Run Tests
script:
  - cd ClientAndServerTesting
  - python3 RequestTest.py
