language: python
python:
 
#Install dependencies
install:
  - pip install -r requirements.txt
  - pip install opencv-python
  - PROTOC_ZIP=protoc-3.7.1-linux-x86_64.zip
  - curl -OL https://github.com/protocolbuffers/protobuf/releases/download/v3.7.1/$PROTOC_ZIP
  - sudo unzip -o $PROTOC_ZIP -d /usr/local bin/protoc
  - sudo unzip -o $PROTOC_ZIP -d /usr/local 'include/*'
  - rm -f $PROTOC_ZIP
  - cd models/research  
  - protoc object_detection/protos/*.proto --python_out=.


#Run Tests
before_script:
  #- cd ClientAndServerTesting
  #- cd object\ detection
  - cd $TRAVIS_BUILD_DIR
  - ls
script:
  - pytest test_object_detection.py
  - python3 ./ClientAndServerTesting/newRequestTest.py