language: python
python:
 
#Install dependencies
install:
  - pip install -r requirements.txt

#Run Tests
before_script:
  #- cd ClientAndServerTesting
   - cd object_detection

script:
 # - python3 newRequestTest.py
  - pytest testing/