language: python
python:
 
#Install dependencies
before_install:
  - pip install -r requirements.txt
  - pip install pip 
  - sudo apt-get update
  - sudo pip install requests
  - cd ClientAndServerTesting
install:

#Run Tests
script:
  - python3 RequestTest.py
