language: python
python:
 
#Install dependencies
install:
  - pip install -r requirements.txt
  - pip install opencv-python
  - protoc object_detection/protos/*.proto --python_out=.


#Run Tests
before_script:
  #- cd ClientAndServerTesting
  #- cd object\ detection

script:
  - pytest test_object_detection.py
  - python3 ./ClientAndServerTesting/newRequestTest.py