language: python
python:
 
#Install dependencies
before_install:
  - sudo apt-get update
install:
  - pip install -r requirements.txt

#Run Tests
script:
  - cd ClientAndServerTesting
  - python3 RequestTest.py
