language: python
python:
 
#Install dependencies
before_install:
  - sudo apt-get update
  - sudo pip install requests
install:
  - pip install -r requirements.txt

#Run Tests
script:
  - cd ClientAndServerTesting
  - python RequestTest.py
