language: python
python:
 
#Install dependencies
install:
  - pip install -r requirements.txt

#Run Tests
before_script:
  #- cd ClientAndServerTesting
  #- cd object\ detection

script:
  - pytest test_object_Detection.py
  - python3 ./ClientAndServerTesting/newRequestTest.py